name: Docker Image CI

on:
  push:
    branches:
    - master
    - release/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Update submodules
      run: git submodule update --init --recursive
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag gentle:$(date +%s)
